export const NEW_ITEM_REQUEST = "NEW_ITEM_REQUEST";
export const NEW_ITEM_SUCCESS = "NEW_ITEM_SUCCESS";
export const NEW_ITEM_FAIL = "NEW_ITEM_FAIL";

export const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAIL = "DELETE_ITEM_FAIL";

export const ITEM_COMPLETE_REQUEST = "ITEM_COMPLETE_REQUEST";
export const ITEM_COMPLETE_SUCCESS = "ITEM_COMPLETE_SUCCESS";
export const ITEM_COMPLETE_FAIL = "ITEM_COMPLETE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
